<?php
/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TimAuth
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'name',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'pwd',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'domain',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'resource',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'termtyp',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
        6 => array(
            'var' => 'token',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        7 => array(
            'var' => 'extend',
            'isRequired' => false,
            'type' => TType::MAP,
            'ktype' => TType::STRING,
            'vtype' => TType::STRING,
            'key' => array(
                'type' => TType::STRING,
            ),
            'val' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var string
     */
    public $name = null;
    /**
     * @var string
     */
    public $pwd = null;
    /**
     * @var string
     */
    public $domain = null;
    /**
     * @var string
     */
    public $resource = null;
    /**
     * @var int
     */
    public $termtyp = null;
    /**
     * @var int
     */
    public $token = null;
    /**
     * @var array
     */
    public $extend = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['name'])) {
                $this->name = $vals['name'];
            }
            if (isset($vals['pwd'])) {
                $this->pwd = $vals['pwd'];
            }
            if (isset($vals['domain'])) {
                $this->domain = $vals['domain'];
            }
            if (isset($vals['resource'])) {
                $this->resource = $vals['resource'];
            }
            if (isset($vals['termtyp'])) {
                $this->termtyp = $vals['termtyp'];
            }
            if (isset($vals['token'])) {
                $this->token = $vals['token'];
            }
            if (isset($vals['extend'])) {
                $this->extend = $vals['extend'];
            }
        }
    }

    public function getName()
    {
        return 'TimAuth';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->pwd);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->domain);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->resource);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->termtyp);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->token);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::MAP) {
                        $this->extend = array();
                        $_size59 = 0;
                        $_ktype60 = 0;
                        $_vtype61 = 0;
                        $xfer += $input->readMapBegin($_ktype60, $_vtype61, $_size59);
                        for ($_i63 = 0; $_i63 < $_size59; ++$_i63) {
                            $key64 = '';
                            $val65 = '';
                            $xfer += $input->readString($key64);
                            $xfer += $input->readString($val65);
                            $this->extend[$key64] = $val65;
                        }
                        $xfer += $input->readMapEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TimAuth');
        if ($this->name !== null) {
            $xfer += $output->writeFieldBegin('name', TType::STRING, 1);
            $xfer += $output->writeString($this->name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->pwd !== null) {
            $xfer += $output->writeFieldBegin('pwd', TType::STRING, 2);
            $xfer += $output->writeString($this->pwd);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->domain !== null) {
            $xfer += $output->writeFieldBegin('domain', TType::STRING, 3);
            $xfer += $output->writeString($this->domain);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->resource !== null) {
            $xfer += $output->writeFieldBegin('resource', TType::STRING, 4);
            $xfer += $output->writeString($this->resource);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->termtyp !== null) {
            $xfer += $output->writeFieldBegin('termtyp', TType::BYTE, 5);
            $xfer += $output->writeByte($this->termtyp);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->token !== null) {
            $xfer += $output->writeFieldBegin('token', TType::I64, 6);
            $xfer += $output->writeI64($this->token);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->extend !== null) {
            if (!is_array($this->extend)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('extend', TType::MAP, 7);
            $output->writeMapBegin(TType::STRING, TType::STRING, count($this->extend));
            foreach ($this->extend as $kiter66 => $viter67) {
                $xfer += $output->writeString($kiter66);
                $xfer += $output->writeString($viter67);
            }
            $output->writeMapEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
