/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@file:Suppress("ClassName", "PropertyName", "RedundantUnitReturnType", "NestedLambdaShadowedImplicitParameter", "RemoveRedundantQualifierName")
package io.github.donnie4w.tim.stub

data class Tid(
  private var _node: kotlin.String? = null,
  var domain: kotlin.String? = null,
  var resource: kotlin.String? = null,
  var termtyp: kotlin.Byte? = null,
  var extend: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
) : org.apache.thrift.TBase<Tid, Tid._Fields> {
  val node: kotlin.String get() = _node!!
  enum class _Fields(private val thriftFieldId: kotlin.Short, private val fieldName: kotlin.String) : org.apache.thrift.TFieldIdEnum {
    NODE(1, "node"),
    DOMAIN(2, "domain"),
    RESOURCE(3, "resource"),
    TERMTYP(4, "termtyp"),
    EXTEND(5, "extend");

    override fun getThriftFieldId() = thriftFieldId

    override fun getFieldName() = fieldName

    companion object {
      @kotlin.jvm.JvmStatic
      fun findByValue(value: kotlin.Int): _Fields? {
        return when (value) {
          1 -> NODE
          2 -> DOMAIN
          3 -> RESOURCE
          4 -> TERMTYP
          5 -> EXTEND
          else -> null
        }
      }

      @kotlin.jvm.JvmStatic
      fun findByName(name: kotlin.String): _Fields? {
        return when (name) {
          "node" -> NODE
          "domain" -> DOMAIN
          "resource" -> RESOURCE
          "termtyp" -> TERMTYP
          "extend" -> EXTEND
          else -> null
        }
      }
    }
  }

  companion object {
    private val STRUCT_DESC: org.apache.thrift.protocol.TStruct = org.apache.thrift.protocol.TStruct("Tid")
    private val NODE_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("node", org.apache.thrift.protocol.TType.STRING, 1)
    private val NODE_FIELD_META_DATA: org.apache.thrift.meta_data.FieldMetaData = org.apache.thrift.meta_data.FieldMetaData(
      "node",
      org.apache.thrift.TFieldRequirementType.REQUIRED,
      org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
      emptyMap())
    private val DOMAIN_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("domain", org.apache.thrift.protocol.TType.STRING, 2)
    private val DOMAIN_FIELD_META_DATA: org.apache.thrift.meta_data.FieldMetaData = org.apache.thrift.meta_data.FieldMetaData(
      "domain",
      org.apache.thrift.TFieldRequirementType.OPTIONAL,
      org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
      emptyMap())
    private val RESOURCE_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("resource", org.apache.thrift.protocol.TType.STRING, 3)
    private val RESOURCE_FIELD_META_DATA: org.apache.thrift.meta_data.FieldMetaData = org.apache.thrift.meta_data.FieldMetaData(
      "resource",
      org.apache.thrift.TFieldRequirementType.OPTIONAL,
      org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
      emptyMap())
    private val TERMTYP_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("termtyp", org.apache.thrift.protocol.TType.BYTE, 4)
    private val TERMTYP_FIELD_META_DATA: org.apache.thrift.meta_data.FieldMetaData = org.apache.thrift.meta_data.FieldMetaData(
      "termtyp",
      org.apache.thrift.TFieldRequirementType.OPTIONAL,
      org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE),
      emptyMap())
    private val EXTEND_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("extend", org.apache.thrift.protocol.TType.MAP, 5)
    private val EXTEND_FIELD_META_DATA: org.apache.thrift.meta_data.FieldMetaData = org.apache.thrift.meta_data.FieldMetaData(
      "extend",
      org.apache.thrift.TFieldRequirementType.OPTIONAL,
      org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
        org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
        org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)),
      emptyMap())
    private val metadata: Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> = mapOf(
      _Fields.NODE to NODE_FIELD_META_DATA,
      _Fields.DOMAIN to DOMAIN_FIELD_META_DATA,
      _Fields.RESOURCE to RESOURCE_FIELD_META_DATA,
      _Fields.TERMTYP to TERMTYP_FIELD_META_DATA,
      _Fields.EXTEND to EXTEND_FIELD_META_DATA,
    )
    init {
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Tid::class.java, metadata)
    }
  }

  private object TidStandardScheme : org.apache.thrift.scheme.StandardScheme<Tid>() {
    override fun read(iproto: org.apache.thrift.protocol.TProtocol, struct: Tid) {
      iproto.apply {
        readStruct {
          var stopped = false
          while (!stopped) {
            stopped = readField {
              val skipNext = { org.apache.thrift.protocol.TProtocolUtil.skip(iproto, it.type) }
              when (it.id.toInt()) {
                1 -> {
                  if (it.type == org.apache.thrift.protocol.TType.STRING) {
                    struct._node = readString()
                  } else {
                    skipNext()
                  }
                }
                2 -> {
                  if (it.type == org.apache.thrift.protocol.TType.STRING) {
                    struct.domain = readString()
                  } else {
                    skipNext()
                  }
                }
                3 -> {
                  if (it.type == org.apache.thrift.protocol.TType.STRING) {
                    struct.resource = readString()
                  } else {
                    skipNext()
                  }
                }
                4 -> {
                  if (it.type == org.apache.thrift.protocol.TType.BYTE) {
                    struct.termtyp = readByte()
                  } else {
                    skipNext()
                  }
                }
                5 -> {
                  if (it.type == org.apache.thrift.protocol.TType.MAP) {
                    struct.extend = readMap { tmap ->
                      kotlin.collections.List(tmap.size) {
                        readString() to readString()
                      }.associate { it }
                    }
                  } else {
                    skipNext()
                  }
                }
                else -> skipNext()
              }
            }
          }
          struct.validate()
        }
      }
    }

    override fun write(oproto: org.apache.thrift.protocol.TProtocol, struct: Tid) {
      struct.validate()
      oproto.apply {
        writeStruct(STRUCT_DESC) {
          struct.node.let { node ->
            writeField(NODE_FIELD_DESC) {
              writeString(node)
            }
          }
          struct.domain?.let { domain ->
            writeField(DOMAIN_FIELD_DESC) {
              writeString(domain)
            }
          }
          struct.resource?.let { resource ->
            writeField(RESOURCE_FIELD_DESC) {
              writeString(resource)
            }
          }
          struct.termtyp?.let { termtyp ->
            writeField(TERMTYP_FIELD_DESC) {
              writeByte(termtyp)
            }
          }
          struct.extend?.let { extend ->
            writeField(EXTEND_FIELD_DESC) {
              writeMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, extend) { (key, value) ->
                writeString(key)
                writeString(value)
              }
            }
          }
          writeFieldStop()
        }
      }
    }

  }

  override fun compareTo(other: Tid?): kotlin.Int {
    val comparator = compareBy<Tid> { it::class.java.name }
      .thenBy { it.node } 
      .thenBy { it.domain } 
      .thenBy { it.resource } 
      .thenBy { it.termtyp } 
      .thenBy(org.apache.thrift.TBaseHelper::compareTo) { it.extend } 
    return nullsFirst(comparator).compare(this, other)
  }

  override fun fieldForId(fieldId: kotlin.Int): _Fields {
    return _Fields.findByValue(fieldId) ?: throw kotlin.IllegalArgumentException("invalid fieldId $fieldId")
  }

  override fun getFieldValue(field: _Fields): kotlin.Any? {
    return when (field) {
      _Fields.NODE -> this.node
      _Fields.DOMAIN -> this.domain
      _Fields.RESOURCE -> this.resource
      _Fields.TERMTYP -> this.termtyp
      _Fields.EXTEND -> this.extend
    }
  }

  @Suppress("UNCHECKED_CAST")
  override fun setFieldValue(field: _Fields, value: kotlin.Any?): kotlin.Unit {
    when (field) {
      _Fields.NODE -> this._node = value as kotlin.String?
      _Fields.DOMAIN -> this.domain = value as kotlin.String?
      _Fields.RESOURCE -> this.resource = value as kotlin.String?
      _Fields.TERMTYP -> this.termtyp = value as kotlin.Byte?
      _Fields.EXTEND -> this.extend = value as kotlin.collections.Map<kotlin.String, kotlin.String>?
    }
  }

  override fun isSet(field: _Fields): kotlin.Boolean {
    return when (field) {
      _Fields.NODE -> this._node != null
      _Fields.DOMAIN -> this.domain != null
      _Fields.RESOURCE -> this.resource != null
      _Fields.TERMTYP -> this.termtyp != null
      _Fields.EXTEND -> this.extend != null
    }
  }

  override fun deepCopy(): Tid {
    return Tid (
      node,
      domain,
      resource,
      termtyp,
      extend,
    )
  }

  override fun clear(): kotlin.Unit {
    _node = null
    domain = null
    resource = null
    termtyp = null
    extend = null
  }

  @kotlin.jvm.Throws(org.apache.thrift.TException::class)
  fun validate(): kotlin.Unit {
    if (_node == null) {
      throw org.apache.thrift.TException("Required field `node' is null, struct is: $this")
    }
  }

  override fun read(iproto: org.apache.thrift.protocol.TProtocol): kotlin.Unit {
    require(org.apache.thrift.scheme.StandardScheme::class.java == iproto.scheme) { "only standard scheme is supported for now" }
    TidStandardScheme.read(iproto, this)
  }

  override fun write(oproto: org.apache.thrift.protocol.TProtocol): kotlin.Unit {
    require(org.apache.thrift.scheme.StandardScheme::class.java == oproto.scheme) { "only standard scheme is supported for now" }
    TidStandardScheme.write(oproto, this)
  }

}
